# Generated by Django 2.2.1 on 2021-04-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListUser',
        ),
    ]
